INSERT INTO `Players_p` 1,"Cairo Foley",25,"Male","Asian","GK","RIght",54,40;
INSERT INTO `Players_p` 2,"Declan Wallace",27,"Male","Asian","CF","Left",5,11;
INSERT INTO `Players_p` 3,"Grant Velez",23,"Male","South American","CB","RIght",56,47;
INSERT INTO `Players_p` 4,"Dominic Miller",25,"Male","Asian","CF","Left",87,2;
INSERT INTO `Players_p` 5,"Adrian Hayes",21,"Male","South American","CM","Both",21,44;
INSERT INTO `Players_p` 6,"Galvin Haley",24,"Male","European","CAM","Left",15,3;
INSERT INTO `Players_p` 7,"Wing Moses",30,"Male","African","CF","Both",14,22;
INSERT INTO `Players_p` 8,"Sylvester Fischer",27,"Male","African","CF","RIght",48,41;
INSERT INTO `Players_p` 9,"Samuel Levine",20,"Male","Asian","WF","Both",117,38;
INSERT INTO `Players_p` 10,"Benedict Baker",22,"Male","South American","CF","Left",108,49;
INSERT INTO `Players_p` 11,"Gareth Kinney",22,"Male","Asian","GK","Left",34,16;
INSERT INTO `Players_p` 12,"Vincent Montgomery",23,"Male","African","CAM","Left",87,29;
INSERT INTO `Players_p` 13,"Richard Jacobson",22,"Male","Asian","WF","Left",66,11;
INSERT INTO `Players_p` 14,"Hayden Schneider",22,"Male","North American","CDM","Left",57,1;
INSERT INTO `Players_p` 15,"Isaiah Stevenson",23,"Male","South American","CB","RIght",4,27;
INSERT INTO `Players_p` 16,"Tad Lara",22,"Male","European","CDM","RIght",14,48;
INSERT INTO `Players_p` 17,"Beck Gay",30,"Male","European","CM","Both",57,13;
INSERT INTO `Players_p` 18,"Richard Pickett",23,"Male","Asian","WF","Left",103,39;
INSERT INTO `Players_p` 19,"Adam Giles",22,"Male","North American","CM","RIght",8,1;
INSERT INTO `Players_p` 20,"Lyle Bright",22,"Male","North American","CDM","RIght",95,33;
INSERT INTO `Players_p` 21,"Todd Cox",21,"Male","North American","CAM","Both",79,47;
INSERT INTO `Players_p` 22,"Aristotle Baker",20,"Male","European","CDM","Left",59,37;
INSERT INTO `Players_p` 23,"Amir Coffey",21,"Male","European","CAM","Left",20,13;
INSERT INTO `Players_p` 24,"Aquila Fry",30,"Male","European","CF","Both",44,33;
INSERT INTO `Players_p` 25,"Wing Rosa",24,"Male","European","CDM","Left",22,12;
INSERT INTO `Players_p` 26,"Joshua Graham",28,"Male","North American","WF","Left",70,16;
INSERT INTO `Players_p` 27,"Castor Lynn",27,"Male","European","CF","Left",58,20;
INSERT INTO `Players_p` 28,"Dennis Pace",27,"Male","Asian","CM","RIght",80,12;
INSERT INTO `Players_p` 29,"Barclay English",24,"Male","South American","CM","RIght",54,25;
INSERT INTO `Players_p` 30,"Jonas Chen",28,"Male","European","CDM","Left",37,20;
INSERT INTO `Players_p` 31,"Timon Alford",23,"Male","African","CF","RIght",20,11;
INSERT INTO `Players_p` 32,"Chase Gentry",29,"Male","European","GK","RIght",20,37;
INSERT INTO `Players_p` 33,"Bruno Joyner",26,"Male","European","CB","RIght",70,28;
INSERT INTO `Players_p` 34,"Steven Boyd",25,"Male","Asian","GK","Left",18,5;
INSERT INTO `Players_p` 35,"Daniel Hogan",27,"Male","European","GK","Both",8,43;
INSERT INTO `Players_p` 36,"Joseph Morris",22,"Male","North American","CAM","RIght",104,4;
INSERT INTO `Players_p` 37,"Cyrus Santos",29,"Male","Asian","FB","RIght",104,50;
INSERT INTO `Players_p` 38,"Wallace Alston",21,"Male","African","FB","RIght",41,5;
INSERT INTO `Players_p` 39,"Dante Patrick",30,"Male","African","WF","RIght",63,34;
INSERT INTO `Players_p` 40,"Quinlan Singleton",21,"Male","European","CM","RIght",97,12;
INSERT INTO `Players_p` 41,"Raphael Larson",29,"Male","European","CF","RIght",110,41;
INSERT INTO `Players_p` 42,"Valentine Boyer",27,"Male","Asian","CAM","Both",22,30;
INSERT INTO `Players_p` 43,"Edan Sawyer",25,"Male","Asian","CDM","RIght",61,2;
INSERT INTO `Players_p` 44,"Jamal Holcomb",21,"Male","European","CAM","Both",15,36;
INSERT INTO `Players_p` 45,"Colby Gallegos",24,"Male","African","CF","RIght",64,35;
INSERT INTO `Players_p` 46,"Zachary Kirkland",20,"Male","South American","CAM","Left",84,42;
INSERT INTO `Players_p` 47,"Fletcher Beard",26,"Male","European","CM","Left",72,49;
INSERT INTO `Players_p` 48,"Quentin Riddle",21,"Male","African","CM","Left",106,33;
INSERT INTO `Players_p` 49,"Gray Kirby",23,"Male","Asian","GK","Both",11,19;
INSERT INTO `Players_p` 50,"Kyle Carpenter",24,"Male","Asian","CDM","Left",15,18;
INSERT INTO `Players_p` 51,"Gavin Manning",28,"Male","Asian","GK","Left",94,39;
INSERT INTO `Players_p` 52,"Arsenio Kelley",24,"Male","Asian","CM","Both",12,26;
INSERT INTO `Players_p` 53,"Ray Griffin",21,"Male","South American","GK","Both",42,46;
INSERT INTO `Players_p` 54,"Oren Zamora",26,"Male","Asian","FB","Left",37,47;
INSERT INTO `Players_p` 55,"Prescott Stout",25,"Male","African","CAM","Left",15,20;
INSERT INTO `Players_p` 56,"Geoffrey Sweeney",28,"Male","Asian","CF","Left",52,34;
INSERT INTO `Players_p` 57,"Nehru Hart",27,"Male","European","CF","Left",15,30;
INSERT INTO `Players_p` 58,"Reed Robinson",23,"Male","North American","CM","Both",112,19;
INSERT INTO `Players_p` 59,"Plato Garner",24,"Male","Asian","GK","RIght",99,17;
INSERT INTO `Players_p` 60,"Price Estrada",21,"Male","South American","FB","RIght",50,22;
INSERT INTO `Players_p` 61,"Chadwick Serrano",29,"Male","South American","CB","RIght",66,45;
INSERT INTO `Players_p` 62,"Harlan Miller",21,"Male","Asian","CF","Left",34,17;
INSERT INTO `Players_p` 63,"Hasad Garrett",28,"Male","European","GK","Both",54,31;
INSERT INTO `Players_p` 64,"Steven Hunt",27,"Male","North American","WF","RIght",49,35;
INSERT INTO `Players_p` 65,"Brenden Dominguez",25,"Male","European","FB","RIght",72,34;
INSERT INTO `Players_p` 66,"Kennan Ingram",29,"Male","North American","CB","RIght",66,35;
INSERT INTO `Players_p` 67,"Omar Riley",25,"Male","South American","CM","RIght",87,47;
INSERT INTO `Players_p` 68,"Addison Kirk",22,"Male","African","CM","Left",105,33;
INSERT INTO `Players_p` 69,"Hall Carney",28,"Male","South American","CF","Both",112,15;
INSERT INTO `Players_p` 70,"Zahir Osborn",22,"Male","Asian","CDM","RIght",10,6;
INSERT INTO `Players_p` 71,"Phelan Dunlap",28,"Male","North American","CB","Left",33,43;
INSERT INTO `Players_p` 72,"Zeus Simon",29,"Male","European","CB","Left",93,46;
INSERT INTO `Players_p` 73,"Richard Cochran",21,"Male","African","GK","Both",65,5;
INSERT INTO `Players_p` 74,"Quinn Brady",30,"Male","South American","CB","Both",98,34;
INSERT INTO `Players_p` 75,"Rudyard Wilkins",26,"Male","African","GK","RIght",100,7;
INSERT INTO `Players_p` 76,"Marshall Luna",20,"Male","African","CAM","Left",107,11;
INSERT INTO `Players_p` 77,"Garrison Williamson",22,"Male","Asian","FB","Left",19,44;
INSERT INTO `Players_p` 78,"Todd Hayes",25,"Male","European","CB","RIght",54,16;
INSERT INTO `Players_p` 79,"Gage Strickland",25,"Male","African","CM","Left",53,4;
INSERT INTO `Players_p` 80,"Dane Trujillo",27,"Male","Asian","FB","RIght",59,43;
INSERT INTO `Players_p` 81,"Brian Pacheco",28,"Male","African","CF","Both",75,48;
INSERT INTO `Players_p` 82,"Joel Merritt",20,"Male","North American","CF","Both",12,41;
INSERT INTO `Players_p` 83,"Benedict Crawford",22,"Male","European","CM","RIght",119,24;
INSERT INTO `Players_p` 84,"Zane Giles",21,"Male","Asian","WF","RIght",62,9;
INSERT INTO `Players_p` 85,"Aladdin Parsons",26,"Male","European","CAM","Both",65,13;
INSERT INTO `Players_p` 86,"Craig Pratt",27,"Male","North American","WF","Left",108,50;
INSERT INTO `Players_p` 87,"Allen Dickson",30,"Male","Asian","CAM","Left",119,29;
INSERT INTO `Players_p` 88,"Dillon Copeland",23,"Male","African","CM","RIght",113,19;
INSERT INTO `Players_p` 89,"Wyatt Conrad",29,"Male","South American","CM","RIght",29,9;
INSERT INTO `Players_p` 90,"Brennan Sawyer",25,"Male","South American","CF","RIght",96,7;
INSERT INTO `Players_p` 91,"Alfonso Lancaster",23,"Male","European","CM","RIght",84,37;
INSERT INTO `Players_p` 92,"Hakeem Fitzpatrick",28,"Male","Asian","GK","Left",66,16;
INSERT INTO `Players_p` 93,"Demetrius Burt",20,"Male","African","CDM","RIght",8,16;
INSERT INTO `Players_p` 94,"Amir Dale",24,"Male","North American","FB","Both",106,4;
INSERT INTO `Players_p` 95,"Ross Stokes",25,"Male","North American","WF","RIght",42,29;
INSERT INTO `Players_p` 96,"Baxter Donovan",24,"Male","South American","FB","Both",48,20;
INSERT INTO `Players_p` 97,"Tyrone Townsend",29,"Male","North American","FB","Left",86,36;
INSERT INTO `Players_p` 98,"Cole Estes",25,"Male","North American","WF","Both",27,38;
INSERT INTO `Players_p` 99,"Joshua Burke",29,"Male","Asian","CM","RIght",66,49;
INSERT INTO `Players_p` 100,"Ralph Vinson",28,"Male","Asian","CDM","Left",104,20;